/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a file
         * @description Sends the content of the file at `path` (HEAD sends the headers
         *     only). Supports byte ranges (`Range`, single and multiple, `If-Range`)
         *     and conditional requests with the `ETag` and `Last-Modified` values
         *     (`If-None-Match`, `If-Modified-Since`, `If-Match`,
         *     `If-Unmodified-Since`). The body's Content-Type is the file's media
         *     type. `Content-Disposition` is always `attachment`, with the name
         *     as an ASCII `filename` and the exact UTF-8 name as `filename*`
         *     (RFC 6266, RFC 8187). Folders and links are refused (400).
         */
        get: operations["downloadFile"];
        /**
         * Upload a file (simple, streamed)
         * @description Writes the request body to the file at `path`. The body is the raw
         *     file content; its Content-Type is not used. `Content-Length` is
         *     required (411 without it): the size is checked against the upload
         *     limit (413) and the free space (507) before anything is stored.
         *     The bytes go to a hidden temporary file in the target folder,
         *     which is synced and then renamed in one step, so the file never
         *     appears partly written. When the name is taken, `on_conflict`
         *     decides: `fail` (409, before the body is read), `rename`
         *     (`name (1).ext`, ...), or `overwrite`, which replaces a file
         *     atomically (200) and never a folder (409). For large files, prefer
         *     the resumable tus upload.
         */
        put: operations["uploadFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a folder
         * @description Creates the folder at `path`. With `parents`, missing parent folders
         *     are created too. When the name is taken, `on_conflict` decides:
         *     `fail` (409), `rename` (`name (1)`, `name (2)`, ...), or `overwrite`,
         *     which returns an existing folder unchanged (200) and never replaces
         *     a file (409). Every new name must follow the name rules.
         */
        post: operations["createFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/operations/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rename a file or folder
         * @description Gives the item at `path` the name `new_name` in the same folder.
         *     `new_name` is one name (no `/`) and must follow the name rules. A
         *     change of case only (`a.txt` to `A.txt`) works on every disk. When
         *     the name is taken, `on_conflict` decides: `fail` (409), `rename`
         *     (`name (1).ext`), or `overwrite`, which replaces a file with a file
         *     and never replaces or merges a folder (409).
         */
        post: operations["renameItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/operations/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move a file or folder
         * @description Moves the item at `from` to the path `to` (the full new path, so a
         *     move can also rename). The parent folder of `to` must exist. A
         *     folder cannot be moved into itself or below itself (400). Conflicts
         *     are handled as for rename.
         */
        post: operations["moveItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/operations/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy a file or folder
         * @description Copies the item at `from` to the path `to` (its parent must exist).
         *     Folders are copied with everything in them; modification times are
         *     kept. The whole source is checked first: the synchronous copy
         *     limits (422 `too_large_for_sync` above `copy.sync_max_items` or
         *     `copy.sync_max_bytes`), the name rules for every new name, links
         *     or special files in the tree (400; links are never followed), and
         *     the free space (507). The copy appears only when it is complete.
         *     A folder cannot be copied into itself (400). Conflicts are handled
         *     as for move; `overwrite` replacing a file answers 200.
         */
        post: operations["copyItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/uploads/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a resumable upload (tus)
         * @description tus "creation": send `Tus-Resumable: 1.0.0`, `Upload-Length`, and
         *     `Upload-Metadata` with `target_path` (required), `on_conflict`, and
         *     `sha256` (base64 values, as tus defines). The target is checked
         *     at once, as for the simple upload. With a body
         *     (creation-with-upload, `Content-Type: application/offset+octet-stream`)
         *     the data starts at once; if it completes the upload, the file is
         *     made and `Item-Path` names it. Every error is a problem.
         */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/uploads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel a resumable upload (tus termination) */
        delete: operations["terminateUpload"];
        options?: never;
        /** Get the offset of a resumable upload (tus) */
        head: operations["getUploadOffset"];
        /**
         * Send more bytes of a resumable upload (tus)
         * @description Send `Upload-Offset` and `Content-Type: application/offset+octet-stream`;
         *     the body may be at most `uploads.max_chunk_size`. The request that
         *     sends the last byte also makes the file (checksum, conflict
         *     policy); `Item-Path` names it. If that fails, the upload is removed.
         */
        patch: operations["appendUpload"];
        trace?: never;
    };
    "/files/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a folder, or get the details of a file
         * @description For a folder, returns the folder and one page of its items, sorted
         *     and paged as described in docs/api/conventions.md. For a file,
         *     returns only the file (the paging parameters do not apply).
         */
        get: operations["getItems"];
        put?: never;
        post?: never;
        /**
         * Delete a file or folder
         * @description Deletes the item at `path` permanently (a trash comes in a later
         *     stage). A symbolic link is deleted itself, never what it points
         *     to. A folder with anything in it needs `recursive=true` (409
         *     otherwise). The root folder cannot be deleted (400). A recursive
         *     delete that fails part-way leaves the rest; repeating it finishes
         *     it.
         */
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server health and startup checks
         * @description Runs the health checks (config, storage_writable, same_filesystem,
         *     free_space, database). A warning keeps the status 200; a failed
         *     check gives 503 with the same report body.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reserved for the photos area
         * @description The photos area has no API before the media stages. This path and
         *     every path under `/photos/`, with any method, answer
         *     `501 not_available`.
         */
        get: operations["getPhotos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FileItem: {
            /** @description The item's path in the caller's files area, starting with `/`. */
            path: string;
            /** @description The last element of the path; empty for the root. */
            name: string;
            kind: components["schemas"]["ItemKind"];
            /**
             * Format: int64
             * @description The size in bytes (0 for folders).
             */
            size: number;
            /**
             * Format: date-time
             * @description The last modification time, in UTC.
             */
            mod_time: string;
            /**
             * @description The media type of a file. In a listing it comes from the file
             *     name's extension only (absent when unknown); for a single file it
             *     falls back to sniffing the first 512 bytes.
             */
            mime?: string;
            /**
             * @description A strong entity tag of the file's current version (only for a
             *     single file, not in listings). It changes when the file is
             *     written or replaced; the download sends the same value.
             */
            etag?: string;
        };
        /**
         * @description A symbolic link is listed but never followed.
         * @enum {string}
         */
        ItemKind: "file" | "dir" | "symlink" | "other";
        ItemsResponse: {
            item: components["schemas"]["FileItem"];
            /** @description For a folder, this page of its items. */
            items?: components["schemas"]["FileItem"][];
            /** @description Present when more items follow; pass it as `cursor` to get the next page. */
            next_cursor?: string;
            /** @description For a folder, how many items it has in all pages. */
            total?: number;
        };
        CreateFolderRequest: {
            /** @description The folder to create, starting with `/`. */
            path: string;
            /**
             * @description Also create missing parent folders.
             * @default false
             */
            parents: boolean;
            on_conflict?: components["schemas"]["OnConflict"];
        };
        RenameRequest: {
            /** @description The item to rename, starting with `/`. */
            path: string;
            /** @description The new name (one name, no `/`). */
            new_name: string;
            on_conflict?: components["schemas"]["OnConflict"];
        };
        MoveRequest: {
            /** @description The item to move, starting with `/`. */
            from: string;
            /** @description The item's new path, starting with `/`. */
            to: string;
            on_conflict?: components["schemas"]["OnConflict"];
        };
        CopyRequest: {
            /** @description The item to copy, starting with `/`. */
            from: string;
            /** @description The path of the copy, starting with `/`. */
            to: string;
            on_conflict?: components["schemas"]["OnConflict"];
        };
        /**
         * @default fail
         * @enum {string}
         */
        OnConflict: "fail" | "rename" | "overwrite";
        /**
         * @default name
         * @enum {string}
         */
        ListSort: "name" | "size" | "mod_time" | "kind";
        /**
         * @default asc
         * @enum {string}
         */
        ListOrder: "asc" | "desc";
        /** @description An RFC 9457 problem details object (docs/api/errors.md). */
        Problem: {
            /**
             * @description Always `about:blank` for now; `title` is then the HTTP status text.
             * @enum {string}
             */
            type: "about:blank";
            /** @description The HTTP status text. */
            title: string;
            /** @description The HTTP status code, equal to the response status. */
            status: number;
            /** @description A human-readable explanation for this occurrence. */
            detail?: string;
            /**
             * @description A stable, machine-readable error code.
             * @enum {string}
             */
            code: "internal" | "invalid_request" | "invalid_name" | "outside_root" | "not_found" | "conflict" | "too_large" | "insufficient_storage" | "not_available" | "method_not_allowed" | "length_required" | "precondition_failed" | "range_not_satisfiable" | "too_large_for_sync" | "locked" | "unavailable";
            /** @description The exact rule that was broken, for some codes (for example `reserved_name` for `invalid_name`). */
            rule?: string;
            /** @description The request ID; the same as the `X-Request-ID` header and the server logs. */
            correlation_id?: string;
        };
        HealthReport: {
            status: components["schemas"]["HealthStatus"];
            version: string;
            checks: components["schemas"]["HealthCheck"][];
        };
        HealthCheck: {
            /** @description config, storage_writable, same_filesystem, free_space, or database. */
            name: string;
            status: components["schemas"]["HealthStatus"];
            detail?: string;
            error?: string;
        };
        /** @enum {string} */
        HealthStatus: "ok" | "warn" | "fail";
    };
    responses: {
        /** @description The request is not valid (`invalid_request`, `invalid_name`, or `outside_root`). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No endpoint at this path (`not_found`), or no such item. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The endpoint exists but not with this method (`method_not_allowed`). The `Allow` header lists the methods. */
        MethodNotAllowed: {
            headers: {
                Allow?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The target already exists, or a parent is not a folder (`conflict`). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The upload has no `Content-Length` header (`length_required`). */
        LengthRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A condition of the request does not hold (`precondition_failed`). */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The range is outside the file (`range_not_satisfiable`); `Content-Range` gives the size. */
        RangeNotSatisfiable: {
            headers: {
                "Content-Range"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request is over a size limit (`too_large`). */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The feature is part of the API but not available yet (`not_available`). */
        NotAvailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The operation is too big for one request (`too_large_for_sync`). */
        TooLargeForSync: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The item is busy with another request (`locked`); retry later. */
        Locked: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The write would use the free space kept in reserve (`insufficient_storage`). */
        InsufficientStorage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description An unexpected server error (`internal`); the details are in the server log under the correlation ID. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description A path in the caller's files area, starting with `/` (the root of the area), in Unicode NFC. See docs/api/conventions.md.
         * @example /docs/report.pdf
         */
        Path: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    downloadFile: {
        parameters: {
            query: {
                /**
                 * @description A path in the caller's files area, starting with `/` (the root of the area), in Unicode NFC. See docs/api/conventions.md.
                 * @example /docs/report.pdf
                 */
                path: components["parameters"]["Path"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The whole file. */
            200: {
                headers: {
                    ETag?: string;
                    "Last-Modified"?: string;
                    "Content-Disposition"?: string;
                    "Accept-Ranges"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description The requested ranges (one range, or `multipart/byteranges`). */
            206: {
                headers: {
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Not modified (`If-None-Match` or `If-Modified-Since`). */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            416: components["responses"]["RangeNotSatisfiable"];
            500: components["responses"]["InternalError"];
        };
    };
    uploadFile: {
        parameters: {
            query: {
                /**
                 * @description A path in the caller's files area, starting with `/` (the root of the area), in Unicode NFC. See docs/api/conventions.md.
                 * @example /docs/report.pdf
                 */
                path: components["parameters"]["Path"];
                on_conflict?: components["schemas"]["OnConflict"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description An existing file was replaced (`on_conflict=overwrite`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileItem"];
                };
            };
            /** @description A new file was created (also with `on_conflict=rename`; the item shows the name used). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["Conflict"];
            411: components["responses"]["LengthRequired"];
            413: components["responses"]["TooLarge"];
            500: components["responses"]["InternalError"];
            507: components["responses"]["InsufficientStorage"];
        };
    };
    createFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderRequest"];
            };
        };
        responses: {
            /** @description The folder already existed (`on_conflict=overwrite`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileItem"];
                };
            };
            /** @description The folder was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    renameItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description The item at its new path. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    moveItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description The item at its new path. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    copyItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyRequest"];
            };
        };
        responses: {
            /** @description The copy replaced a file (`on_conflict=overwrite`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileItem"];
                };
            };
            /** @description The copy. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            422: components["responses"]["TooLargeForSync"];
            500: components["responses"]["InternalError"];
            507: components["responses"]["InsufficientStorage"];
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The upload was created; `Location` is its URL. */
            201: {
                headers: {
                    Location?: string;
                    /** @description With a body, how many bytes the server has. */
                    "Upload-Offset"?: number;
                    /** @description When the upload is complete, the path of the file. */
                    "Item-Path"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["Conflict"];
            411: components["responses"]["LengthRequired"];
            412: components["responses"]["PreconditionFailed"];
            413: components["responses"]["TooLarge"];
            500: components["responses"]["InternalError"];
            501: components["responses"]["NotAvailable"];
            507: components["responses"]["InsufficientStorage"];
        };
    };
    terminateUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The upload and its data were removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            412: components["responses"]["PreconditionFailed"];
            423: components["responses"]["Locked"];
        };
    };
    getUploadOffset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description How many bytes the server has. */
            200: {
                headers: {
                    "Upload-Offset"?: number;
                    "Upload-Length"?: number;
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            423: components["responses"]["Locked"];
        };
    };
    appendUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bytes were stored. */
            204: {
                headers: {
                    "Upload-Offset"?: number;
                    /** @description When the upload is complete, the path of the file. */
                    "Item-Path"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            413: components["responses"]["TooLarge"];
            423: components["responses"]["Locked"];
            500: components["responses"]["InternalError"];
            507: components["responses"]["InsufficientStorage"];
        };
    };
    getItems: {
        parameters: {
            query: {
                /**
                 * @description A path in the caller's files area, starting with `/` (the root of the area), in Unicode NFC. See docs/api/conventions.md.
                 * @example /docs/report.pdf
                 */
                path: components["parameters"]["Path"];
                /** @description The `next_cursor` of the previous page. Only valid with the same sort and order. */
                cursor?: string;
                /**
                 * @description Start the page at this position of the sorted folder, as an
                 *     alternative to `cursor` (not both), for jumping to any part of
                 *     a large folder. Items added or removed meanwhile can shift the
                 *     positions; `cursor` never skips or repeats an item.
                 */
                offset?: number;
                /** @description The page size. */
                limit?: number;
                sort?: components["schemas"]["ListSort"];
                order?: components["schemas"]["ListOrder"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The item, and for a folder one page of its items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteItem: {
        parameters: {
            query: {
                /**
                 * @description A path in the caller's files area, starting with `/` (the root of the area), in Unicode NFC. See docs/api/conventions.md.
                 * @example /docs/report.pdf
                 */
                path: components["parameters"]["Path"];
                /** @description Delete a folder with everything in it. */
                recursive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The item was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy, possibly with warnings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            500: components["responses"]["InternalError"];
            /** @description At least one check failed. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
        };
    };
    getPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            500: components["responses"]["InternalError"];
            501: components["responses"]["NotAvailable"];
        };
    };
}
